// Generated by Wrangler by running `wrangler types worker-configuration.d.ts`

interface Env {
	FEEDGEN_PUBLISHER_DID: string;
	FEEDGEN_RECORD_NAME: string;
	ATPROTO_FEED: DurableObjectNamespace<import('./src/index').ATPROTO_FEED>;
}
